### ISSUE TITLE
Lab 9 derivation of ADI method

### ISSUE THREAD

**Issue by ianMaweu** [gustavdelius/NumPDE_2017#7]
Not sure if it is my working out however, when i rearranged the first pair of formulas in Lab 9 I found that the right hand side of both equations was maybe not multiplied by -1.
If this turns out to be case then I think all that needs adjusting is the sign of F1 and F2 in the code for the ADI method.
@gustavdelius

**Comment by gustavdelius** [comment]
Hi Ian. Thank you very much for raising this issue. You are quite right. I have now fixed the Lab and I also added a comparison between the numerical solution and the exact solution. This is something I should have done from the outset and I would have noticed my mistake.
